---
- name: adding backports repository
  apt_repository: repo='deb http://http.debian.net/debian stretch-backports main contrib non-free' state=present update_cache=yes

- name: installing suricata
  apt:
    name: suricata
    state: latest
    default_release: stretch-backports
    update_cache: yes

- name: configuring suricata to listen on "{{ suricata_interface }}"
  template:
    src: "{{ role_path }}/files/suricata.yaml"
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: 0644

- name: fetching emerging rules with oinkmaster
  shell: oinkmaster -C /etc/suricata/suricata-oinkmaster.conf -o /etc/suricata/rules/

- name: restart suricata service
  systemd:
    name: suricata
    state: restarted
